version: '3.8'

services:
  postgres_application:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: iadoc_application_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes: 
      - ./database/application_schema_and_data.sql:/docker-entrypoint-initdb.d/application_schema_and_data.sql
      #- pgdata_application:/var/lib/postgresql/data
    networks:
      - iadoc_network
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  postgres_document:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: iadoc_document_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    expose:
      - 5433
    volumes: 
      - ./database/document_schema_and_data.sql:/docker-entrypoint-initdb.d/document_schema_and_data.sql
      #- pgdata_document:/var/lib/postgresql/data
    networks:
      - iadoc_network
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  postgres_question:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: iadoc_question_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    expose:
      - 5434
    volumes: 
      - ./database/question_schema_and_data.sql:/docker-entrypoint-initdb.d/question_schema_and_data.sql
      #- pgdata_question:/var/lib/postgresql/data
    networks:
      - iadoc_network
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  redis-stack:
    image: redis/redis-stack-server
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - redis-data:/data
    networks:
      - iadoc_network

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 9094:9094
    expose:
      - 9094
    networks:
      - iadoc_network
  
  kafka-connect:
    image: confluentinc/cp-kafka-connect-base:latest
    restart: always
    depends_on:
      - kafka
      - postgres_application
      - postgres_document
      - postgres_question
    ports:
      - 8083:8083
    expose:
      - 8083
    networks:
      - iadoc_network
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars,/etc/kafka-connect/jars
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: false
    command:
      - bash
      - -c
      - |
        echo "Installing Connector jdbc"
        confluent-hub install confluentinc/kafka-connect-jdbc:latest --no-prompt
        #
        echo "Installing Connector postgres"
        confluent-hub install debezium/debezium-connector-postgresql:latest --no-prompt
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        #
        sleep infinity

networks:
  iadoc_network:
    driver: bridge

volumes:
  #pgdata_application:
  #pgdata_document:
  #pgdata_question:
  redis-data: